### ISSUE TITLE
可否添加支持使用代理更新 CeJS

### ISSUE THREAD

**Issue by mengmo** [kanasimi/gh-updater#2]
因为网络的原因，使用`GitHub.updater.node.js`更新 CeJS 时
下载 repository zip 的速度很慢，而且经常中断。

可否自动检测当前的系统代理设置，使用代理进行下载。
或者至少支持 Windows 命令提示符的变量`http_proxy`

**Comment by kanasimi** [comment]
1.3.0添加了功能
要麻煩您試試看了

**Comment by mengmo** [comment]
```
node GitHub.updater.node.js
Read the latest version from cache file CeJS-master.version.json
Get the infomation of latest version of CeJS...
Update: 2019-08-10T06:59:24Z
     → 2019-08-13T06:54:59Z
It seems you using proxy server: http://127.0.0.1:1080. Downloading tool to use proxy server...
安裝執行時需要用到的組件 [cejs]...
Running command at D:\PortableApps\work_crawler: npm install  cejs@latest
npm ERR! Cannot read property 'resolve' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\localhost\node\node_modules\npm-cache\_logs\2019-08-13T16_34_25_603Z-debug.log
child_process.js:669
    throw err;
    ^

Error: Command failed: npm install  cejs@latest
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at update_package (D:\PortableApps\work_crawler\GitHub.updater.node.js:116:27)
    at download_repository_archive (D:\PortableApps\work_crawler\GitHub.updater.node.js:396:4)
    at update_via_7zip (D:\PortableApps\work_crawler\GitHub.updater.node.js:516:2)
    at D:\PortableApps\work_crawler\GitHub.updater.node.js:706:4
    at D:\PortableApps\work_crawler\GitHub.updater.node.js:679:4
    at IncomingMessage.<anonymous> (D:\PortableApps\work_crawler\GitHub.updater.node.js:644:4)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
```
CeJS 安装在当前目录的 CeJS-master 下，应该不需要再`npm install  cejs@latest`了吧？

**Comment by kanasimi** [comment]
這邊沒辦法做這樣的測試，還是要麻煩您試試看
至於您遇到的問題，或許可參考
https://github.com/nodejs/help/issues/1941

**Comment by mengmo** [comment]
目前的情况是可以检测到设置了`http_proxy`，但是下载时根本就不走代理
本来以为是 CeJS 的版本问题，然而这几天连续更新了几次都是这样

**Comment by kanasimi** [comment]
已修改
麻煩請再試試
(得要等到更新完新版CeJS之後才會有效果)
